language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [ -f ${CACHE_FILE_SLAMDATA} ]; then gunzip -c ${CACHE_FILE_SLAMDATA} | docker load; fi

install:
  - sudo apt-get update
  - sudo apt-get install imagemagick
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - convert -version
  - java -version

  - nvm install stable
  - nvm use stable
  - npm install -g bower
  - npm install -g gulp

  - npm i
  - bower install

  - npm link gulp
  - npm run check:quasar
  - gulp add-headers trim-whitespace replace-crlf
  - if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]; then git status && echo -e "\033[31m\n^ CRLF/header/whitespace related problems found\033[0m\n" && exit 1; fi
  - npm run build:icons
  - npm run build:sass
  - npm run build:psa

  - npm run docker:$CONNECTOR_HOST
  - if [ ! -f ${CACHE_FILE_SLAMDATA} ]; then cd ./docker/ && docker save docker_slamdata_$ABV | gzip > ${CACHE_FILE_SLAMDATA}; fi

script:
  - if test $TRAVIS_TAG; then npm run build:bundle-prod && npm run versionify; else npm run build:bundle-prod && npm run test:property && npm test; fi

env:
  matrix:
    - CONNECTOR_TYPE=MongoDB CONNECTOR_PORT=27017 CONNECTOR_HOST=mongo QUASAR_PORT=63176 ABV=md
   # - CONNECTOR_TYPE=Marklogic CONNECTOR_PORT=8000 CONNECTOR_HOST=marklogic QUASAR_PORT=63177 ABV=ml
   # - CONNECTOR_TYPE=Couchbase CONNECTOR_PORT=11210 CONNECTOR_HOST=couchbase QUASAR_PORT=63175 ABV=cb
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_SLAMDATA=$CACHE_DIR/slamdata.tar.gz

cache:
  directories:
  - $CACHE_DIR

before_deploy:
- mkdir -p slamdata
- cp -r public slamdata/
- tar cjf slamdata.tar.bz2 slamdata
deploy:
  provider: releases
  api-key:
    secure: TitL0gINR0xhcMdNBSFKulH7VlS+q1bAkmkWe5H5drTGesqFQprmnoHxPM8Sstfr0DGrAsSKweN/SsUpmVpK8fUE3AcK9kNqt9HXIXr2UotYa1f3jqQKc4+KRXOOf4qjEdUwYRYYMUayR4psA/mijm3WxoVG/jrOjRZAkal/NAY=
  file: slamdata.tar.bz2
  skip_cleanup: true
  on:
    repo: slamdata/slamdata
    branch: master
    tags: true
notifications:
  slack:
    secure: EbxkmDGMm5b2K5tpFrcjEmywSzhU6TSJM6VuCzIfpZ78UWqxQ6u2bbpL5a7FYjYqLZI4U/+7p+M85o0Sj58KHgfwWtpgJn84uKvIkSHo808LU/zmCBuiY4kB4z5AnTXVVFdJ2Lx+vjaeBvZA0XNztdDAViT0QM0nTAs7T94oAW8=
  email:
    on_failure: change
